### ISSUE TITLE
specifying size with percentage

### ISSUE THREAD

**Issue by defvol** [colinta/teacup#49] opened 2012-10-24 16:56 UTC
There are times where I need a subview to expand and fill the parent view, i.e. `subview.frame = parent.bounds`

I believe it would be convenient to have something like this in stylesheets:

```
  style :overlay,
    height: 100%,
    width: 100%,
    backgroundColor: UIColor.colorWithRed(0, green:0, blue:0, alpha:0.5)
```

where `width: 100%` means `subview.frame.size.width == subview.superview.frame.size.width`

any thoughts?

**Comment by farcaller** [comment] 2012-10-24 16:59
I'd suggest a syntax like

```
height: :relative, 0.1
```

**Comment by colinta** [comment] 2012-10-24 17:06
I wonder: what about a number symbol?

```
width: :100
```

Too magic?

Or, actually, a handler would be less invasive:

```
width%: 100
size%: [100, 50]
```

Is that syntax valid? :-/

**Comment by defvol** [comment] 2012-10-24 17:29
it should be easy to distinguish between percentages (or relative sizes) and pixels, so a number symbol seems too magic for me :trollface:

**Comment by ConradIrwin** [comment] 2012-10-24 17:49
Surely the answer is to monkeypatch Fixnum:

width: 100.percent

or to provide a magic function on stylesheets:

width: 0.9 \* parent_width

both of which return a special number-like object

Conrad

**Comment by colinta** [comment] 2012-10-25 15:07
I'd be in favor of monkeypatching Fixnum (or Numeric), but getting a "number like object" is tricky - in plain ruby you can create "delegate" classes to accomplish the same task as subclassing numerics/true/nil, but we don't have that in rubymotion...

That said, it might be as simple as writing a few math methods...

Still, I think we would be entering "bad hack" town if we went that route.

A Percent class could be used explicitly:

```
width: Percent(100)  # returns Percent.new(100)
```

And that could be used outside of the Stylesheet class.

**Comment by colinta** [comment] 2012-10-25 15:19
I'm playing around with this, an honestly I actually like _this_ solution the best so far:

```
size: ['100%', '100%'] / 100.0
```

It's an easy string-to-number conversion, easy to check, and only requires changes to `z_handlers.rb`

**Comment by colinta** [comment] 2012-10-25 15:20
```
> '100%'[0...-1].to_f
=> 100.0
```

**Comment by colinta** [comment] 2012-10-25 16:12
Wait a sec... we are "resolving" a problem that UIKit's 'autolayout' system solves.  We should be talking about how to implement auto layouts in teacup's DSL!

[About Auto Layout](https://developer.apple.com/library/mac/#documentation/UserExperience/Conceptual/AutolayoutPG/Articles/Introduction.html)
[Constraints Express Relationships Between Views](https://developer.apple.com/library/mac/#documentation/UserExperience/Conceptual/AutolayoutPG/Articles/constraintFundamentals.html#//apple_ref/doc/uid/TP40010853-CH2-SW1)
[Dividing Responsibility Between Controllers and Views](https://developer.apple.com/library/mac/#documentation/UserExperience/Conceptual/AutolayoutPG/Articles/dividingResponsibility.html#//apple_ref/doc/uid/TP40010853-CH4-SW1)
[Beginning Auto Layout in iOS 6](http://www.raywenderlich.com/20881/beginning-auto-layout-part-1-of-2)

**Comment by farcaller** [comment] 2012-10-25 17:40
It's not really an issue about autolayout, as we're not going to recalculate the size dynamically, it's merely a convenience issue. Autolayouts are much more advanced.

Also, autolayouts do already have a DSL :)

**Comment by colinta** [comment] 2012-10-25 17:52
True, though the '100%' could be expressed (albeit more verbosely) like this:

``` ruby
  style :thing,
    constraints: [
      constrain(:self, :width).equals(:superview, :width),
      constrain(:self, :height).equals(:superview, :height),
    ]
```

`:self` and `:superview` become reserved stylenames, any other symbol is searched for by stylename.

Whaddya think?  I think this could make some big waves! :-)

**Comment by farcaller** [comment] 2012-10-25 17:59
the problem is, as soon as you name it "constraints", people would expect them to work as autolayout constraints. Which we would hardly implement under iOS5. :wink:

**Comment by colinta** [comment] 2012-10-25 18:33
yeah, they ARE autolayout constraints! This would be an iOS6 only feature.  Autolayout is, in my opinion, just friggin' awesome.  Really does a good job of solving the problem of frame adjustment.

**Comment by defvol** [comment] 2012-10-25 19:38
I agree that it would be better to not reinvent the wheel and take advantage of the autolayout feature in iOS6.

By the way, the `:superview` symbol in the stylesheet could be very useful!

For iOS5 we could just make available a small subset of constraints which depend on reading properties from the superview ... such as the ones previously suggested (100% width, 100% height) ... removing the need for `subview.frame = superview.bounds` or `subview_frame.size.width *= 0.5 superview_frame.size.width` in controllers.

**Comment by colinta** [comment] 2012-10-27 23:51
https://github.com/rubymotion/teacup/tree/relative_width supports the '100%' calculation, and it also lets you assign a _formula_

```
width: ->{|superview| superview.bounds.size.width / 2},
# or maybe
size: [320, ->{|superview| superview.bounds.size.height / 2}]
```

**Comment by colinta** [comment] 2012-12-18 19:09
`relative_width` has been merged in.

**Closed as completed** 2012-12-18 19:17 UTC
